export declare const EnvironmentsUrls: {
    local: {
        SRV_DIRECTORY: string;
        SRV_CALENDAR: string;
        SRV_PROXY_OLD: string;
        SRV_PROXY_OLD_HELSE: string;
        SRV_PROXY_OLD_WEB: string;
        SRV_STORAGE: string;
        SRV_CHAT: string;
        SRV_CONNECTOR: string;
        SRV_ARTIFACT: string;
        SRV_ADVOCA: string;
        SRV_PROXY: string;
        SRV_NOTIFICATION: string;
        SRV_ACTIVITIES: string;
        SRV_AO_DIRECTORY: string;
        SRV_AO_WRAPPER: string;
    };
    dev: {
        SRV_DIRECTORY: string;
        SRV_CALENDAR: string;
        SRV_PROXY_OLD: string;
        SRV_PROXY_OLD_HELSE: string;
        SRV_PROXY_OLD_WEB: string;
        SRV_STORAGE: string;
        SRV_CHAT: string;
        SRV_CONNECTOR: string;
        SRV_ARTIFACT: string;
        SRV_ADVOCA: string;
        SRV_PROXY: string;
        SRV_NOTIFICATION: string;
        SRV_ACTIVITIES: string;
        SRV_AO_DIRECTORY: string;
        SRV_AO_WRAPPER: string;
    };
    test: {
        SRV_DIRECTORY: string;
        SRV_CALENDAR: string;
        SRV_PROXY_OLD: string;
        SRV_PROXY_OLD_HELSE: string;
        SRV_PROXY_OLD_WEB: string;
        SRV_STORAGE: string;
        SRV_CHAT: string;
        SRV_CONNECTOR: string;
        SRV_ARTIFACT: string;
        SRV_ADVOCA: string;
        SRV_PROXY: string;
        SRV_NOTIFICATION: string;
        SRV_ACTIVITIES: string;
        SRV_AO_DIRECTORY: string;
        SRV_AO_WRAPPER: string;
    };
    stage: {
        SRV_DIRECTORY: string;
        SRV_CALENDAR: string;
        SRV_PROXY_OLD: string;
        SRV_PROXY_OLD_HELSE: string;
        SRV_PROXY_OLD_WEB: string;
        SRV_STORAGE: string;
        SRV_CHAT: string;
        SRV_CONNECTOR: string;
        SRV_ARTIFACT: string;
        SRV_ADVOCA: string;
        SRV_PROXY: string;
        SRV_NOTIFICATION: string;
        SRV_ACTIVITIES: string;
        SRV_AO_DIRECTORY: string;
        SRV_AO_WRAPPER: string;
    };
    prod: {
        SRV_DIRECTORY: string;
        SRV_CALENDAR: string;
        SRV_PROXY_OLD: string;
        SRV_PROXY_OLD_HELSE: string;
        SRV_PROXY_OLD_WEB: string;
        SRV_STORAGE: string;
        SRV_CHAT: string;
        SRV_CONNECTOR: string;
        SRV_ARTIFACT: string;
        SRV_ADVOCA: string;
        SRV_PROXY: string;
        SRV_NOTIFICATION: string;
        SRV_ACTIVITIES: string;
        SRV_AO_DIRECTORY: string;
        SRV_AO_WRAPPER: string;
    };
};
export declare function environmentUrls(ENVIRONMENT_TO_OPERATE?: string): {
    SRV_DIRECTORY: string;
    SRV_CALENDAR: string;
    SRV_PROXY_OLD: string;
    SRV_PROXY_OLD_HELSE: string;
    SRV_PROXY_OLD_WEB: string;
    SRV_STORAGE: string;
    SRV_CHAT: string;
    SRV_CONNECTOR: string;
    SRV_ARTIFACT: string;
    SRV_ADVOCA: string;
    SRV_PROXY: string;
    SRV_NOTIFICATION: string;
    SRV_ACTIVITIES: string;
    SRV_AO_DIRECTORY: string;
    SRV_AO_WRAPPER: string;
} | undefined;
export default environmentUrls;
//# sourceMappingURL=EnvironmentsUrls.d.ts.map