export * from './helpers/_processServerError.js'
export * from './helpers/FormatNumberConstants.js'
export * from './helpers/NorwegianPostalCodes.js'
export * from './helpers/CapitalizeFistLetter.js'
export * from './helpers/IsAdcuris.js'
export * from './helpers/IsAdopus.js'
export * from './helpers/IsNotEmpty.js'
export * from './helpers/Config.js'
export * from './helpers/InitializeIDBListenersOnMstSnapshots.js'
export * from './helpers/initEnvConfigsVars.js'

export * from './helpers/getGqlOperationName.js'
export * from './helpers/parseJwt.js'
export * from './helpers/EnvironmentsUrls.js'
export * from './helpers/EnvironmentToOperateTypes.js'
export * from './helpers/generateSrvAuthBindings.js'
export * from './helpers/getSubdomain.js'
//export * from './helpers/checkForRegisteredSubdomains.js'
export * from './helpers/clearCacheData.js'
export * from './helpers/generateGenqlClient.js'
export * from './helpers/generateEnvConfigsBindings.js'
export * from './helpers/userTypingSignal.js'
export * from './helpers/base64ToFile.js'
export * from './helpers/isValidUrl.js'
export * from './helpers/attachUserJournalCredentials.js'
export * from './helpers/initASMAAppVitals.js'
export * from './helpers/registerOpenReplay.js'
export * from './helpers/urlParams.helpers.js'
//export * from './helpers/openReplayConfigs.js'
export * from './helpers/sha256.js'
export * from './helpers/requestIdleCallback.js'

export * from './utility/fetch.js'

export * from './clients/srvAuth.js'

export * from './interfaces/enums.js'

export * from './g-definitions.js'

export * from './helpers/validateNorwegianPersonalNumber.js'
export * from './helpers/generateSyntheticNorwegianNumber.js'
export * from './helpers/generateRandomString.js'
export * from './helpers/isUUID.js'
export * from './helpers/JSONToBase64EncodeDecode.js'
export * from './helpers/getActivityStatus.js'
